# Generated by Django 4.2.20 on 2025-04-14 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="device name")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("WORKSTATION", "Workstation"),
                            ("SERVER", "Server"),
                            ("LAPTOP", "Laptop"),
                            ("NETWORK", "Network Device"),
                            ("MOBILE", "Mobile Device"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="device type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("MAINTENANCE", "Maintenance"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="MAC address"
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="hostname"
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="operating system"
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="OS version"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="manufacturer"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="model"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="serial number"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="last seen"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device",
                "verbose_name_plural": "devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="DeviceSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu",
                    models.CharField(blank=True, max_length=100, verbose_name="CPU"),
                ),
                (
                    "ram_gb",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="RAM (GB)"
                    ),
                ),
                (
                    "storage_gb",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Storage (GB)"
                    ),
                ),
                (
                    "gpu",
                    models.CharField(blank=True, max_length=100, verbose_name="GPU"),
                ),
                (
                    "screen_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="screen size"
                    ),
                ),
                (
                    "battery_health",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="battery health"
                    ),
                ),
                (
                    "additional_specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="additional specifications",
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "device specification",
                "verbose_name_plural": "device specifications",
            },
        ),
    ]
